name: Deploy to EC2

on:
  push:
    branches:
      - main # or whatever branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd /home/ec2-user/workspace/DiscordBot
            git remote set-url origin https://github.com/dakken205/DiscordBot.git
            git pull origin main

      - name: Stop previous process
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd /home/ec2-user/workspace/DiscordBot
            bash stop_previous_process.sh

      - name: Start new process
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd /home/ec2-user/workspace/DiscordBot
            nohup python3 discordbot.py > output.log &
            disown
